"""도메인 — 사실만 담는 계층. 판정 결과는 여기 들어오지 않는다."""

from .certainty import (
    Certainty,
    DeterminationQuality,
    InputQuality,
    LegalStatus,
)
from .models import (
    AcquisitionCause,
    Election,
    ElectionKind,
    Household,
    HouseholdId,
    ImputedResidenceReason,
    InheritedMeta,
    Ownership,
    Person,
    PersonId,
    PersonType,
    PriceFact,
    Property,
    PropertyId,
    PropertyKind,
    RentalRegistration,
    RentalType,
    ResidenceSpell,
    TaxCase,
    TaxYear,
    Won,
    assessment_date,
)

__all__ = [
    "AcquisitionCause",
    "Certainty",
    "DeterminationQuality",
    "Election",
    "ElectionKind",
    "Household",
    "HouseholdId",
    "ImputedResidenceReason",
    "InheritedMeta",
    "InputQuality",
    "LegalStatus",
    "Ownership",
    "Person",
    "PersonId",
    "PersonType",
    "PriceFact",
    "Property",
    "PropertyId",
    "PropertyKind",
    "RentalRegistration",
    "RentalType",
    "ResidenceSpell",
    "TaxCase",
    "TaxYear",
    "Won",
    "assessment_date",
]
